---
- hosts: localhost
  become: true

  tasks:

    - name: apt key for yarn installation added
      apt_key:
        url: https://dl.yarnpkg.com/debian/pubkey.gpg
        state: present

    - name: yarn repository added
      apt_repository:
        repo: deb https://dl.yarnpkg.com/debian/ stable main
        state: present

    - name: required packages installed
      apt:
        name: ['vim', 'zsh', 'wget', 'git', 'curl', 'npm', 'yarn', 'adb']
        state: present
        update_cache: yes

    - name: expo-cli installed
      command: yarn global add expo-cli
      become_user: vagrant

    - name: oh-my-zsh repository cloned
      git:
        repo=https://github.com/robbyrussell/oh-my-zsh.git
        dest=/root/.oh-my-zsh

    - name: oh-my-zsh default configuration generated
      command: cp /root/.oh-my-zsh -r /home/vagrant/.oh-my-zsh

    - name: zsh default configuration generated
      command: cp /root/.oh-my-zsh/templates/zshrc.zsh-template /home/vagrant/.zshrc

    - name: expo command line tool made available
      lineinfile:
        path: /home/vagrant/.zshrc
        line: 'echo "export PATH=$PATH:/home/vagrant/.yarn/bin" >> /home/vagrant/.zshrc'
        create: yes

    - name: zsh configuration file permissions set
      file:
        path: /home/vagrant/.zshrc
        owner: vagrant
        group: vagrant

    - name: vim configuration set
      copy:
        src: "roles/vim/files/vimrc"
        dest: /home/vagrant/.vimrc

    - name: default nodejs version removed
      apt:
        name: ['nodejs']
        state: absent
        update_cache: yes
        purge: true

    - name: gpg key for nodejs 18 LTS installed
      apt_key:
        url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
        state: present

    - name: nodejs 18 LTS repo configured
      apt_repository:
        repo: "deb https://deb.nodesource.com/node_18.x jammy main"
        state: present
        update_cache: yes

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes

    - name: nodejs 18 LTS installed
      apt:
        name: nodejs
        state: present

    - name: corepack enabled
      shell:
        cmd: corepack enable

    - name: yarn latest version installed
      shell:
        cmd: corepack prepare yarn@stable --activate
      become: true
      become_user: vagrant

    - name: eas installed
      npm:
        name: eas-cli
        global: true
        state: present
        become: true
