---
- hosts: localhost
  become: true

  tasks:

    - name: required packages installed
      apt:
        name="{{ item }}"
        state=present
        update_cache=yes
      with_items:
        - vim
        - zsh
        - wget
        - git
        - curl
        - npm

    - name: expo-cli installed
      npm:
        name: expo-cli
        state: present
        global: yes
