---
- hosts: localhost
  become: true

  tasks:

    - name: required packages installed
      apt:
        name="{{ item }}"
        state=present
        update_cache=yes
      with_items:
        - vim
        - zsh
        - wget
        - git
        - curl
        - npm

    - name: expo-cli installed
      npm:
        name: expo-cli
        state: present
        global: yes

    - name: react-native-cli installed
      npm:
        name: react-native-cli
        state: present
        global: yes

    - name: oh-my-zsh repository cloned
      git:
        repo=git://github.com/robbyrussell/oh-my-zsh.git
        dest=/root/.oh-my-zsh

    - name: oh-my-zsh default configuration generated
      command: cp /root/.oh-my-zsh -r /home/vagrant/.oh-my-zsh

    - name: zsh default configuration generated
      command: cp /root/.oh-my-zsh/templates/zshrc.zsh-template /home/vagrant/.zshrc
